### ISSUE TITLE
[新功能] 通过配置文件配置是否每次运行命令都获取公告/检查更新

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Chinese_git#19]
这将加快某些时刻的命令运行速度，但这也将不能使用户获取到最新信息。

> 自定义每执行n次命令就检查一次更新？

**Comment by DuckDuckStudio** [comment]
我刚在看的时候还在找“我的配置文件去哪了”，找了一番发现根本就没有配置文件😂

**Comment by DuckDuckStudio** [comment]
很抱歉耽搁了，由于我需要处理一个新的任务，此任务将被暂停

**Comment by Luna-Grace** [comment]
@DuckDuckStudio 
https://github.com/DuckDuckStudio/Chinese_git/labels/%E5%BE%85%E5%8F%91%E5%B8%83 的Issue是否应该重新打开？

**Comment by DuckDuckStudio** [comment]
> DuckDuckStudio [ 待发布](https://github.com/DuckDuckStudio/Chinese_git/labels/%E5%BE%85%E5%8F%91%E5%B8%83) 已修改完成，等待发布 的Issue是否应该重新打开？

不用

**Comment by fjwxzde** [comment]
自动发布流开始运行

**Comment by DuckDuckStudio** [comment]
> 这个功能还未与更新命令适配

相关讨论移至 #22
