### ISSUE TITLE
[BUG] 执行部分命令时不会有输出，但命令成功执行

### ISSUE THREAD

**Issue by Luna-Grace** [DuckDuckStudio/Chinese_git#26]
*此问题因 Issue #25 由文档转移至此*  
原文:  
在使用 中文Git 执行部分命令时不会有输出，但命令成功执行

**Comment by fjwxzde** [comment]
可能重复
- #3

**Comment by DuckDuckStudio** [comment]
如果有谁可以修复此问题，请提交PR。
这似乎是由于获取输出时的类型引起的？
