### ISSUE TITLE
在未暂存任何内容时提交会提示错误但不给出任何错误信息

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Chinese_git#3]
![image](https://github.com/DuckDuckStudio/Chinese_git/assets/89643991/bd44515a-23fb-45a8-9d56-4833157ee527)
建议：在未暂存任何内容时提交询问是否暂存所有内容后提交
可能：可能可以做个每次都这样，就像Visual Code中的一样

**Comment by Luna-Grace** [comment]
Fixed in commit [a927fc2](https://github.com/DuckDuckStudio/Chinese_git/commit/a927fc276a916fcbaac71c743a4d051e16279b9e)

**Comment by DuckDuckStudio** [comment]
已在 [v2.5](https://github.com/DuckDuckStudio/Chinese_git/releases/tag/v2.5) 中发布修复
