### ISSUE TITLE
[feat] 将中文Git发布至pypi

### ISSUE THREAD

**Issue by nobodxbodon** [DuckDuckStudio/Chinese_git#44]
mac下将 [Chinese_git_py.zip](https://github.com/DuckDuckStudio/Chinese_git/releases/download/v2.9/Chinese_git_py.zip) 解压后目录下运行：

```
% python 中文git.py 
使用方法:
中文git <中文指令> [参数]
即：中文git <你想干什么> [具体要啥]

[!有新公告(3级)!]
[更新说明]
中文Git v2.9 已发布
你可以使用`中文git 更新`命令来更新到最新版本
[!------------!]
```

请问如何安装并执行像 `% 中文git 克隆 ...`？

另外，可否发布到pypi，方便直接安装？

**Comment by DuckDuckStudio** [comment]
1. 我没有mac设备，也没有对应的虚拟机，我也只在Windows上测试过。
2. 对于发布到pypi...我想，但是我不会弄。

**Comment by nobodxbodon** [comment]
[供参考](https://gitee.com/MulanRevive/mulan-rework/blob/master/pyproject.toml)，已发布在pypi。安装 [ulang](https://pypi.org/project/ulang/) 后可运行 `木兰 xx.ul`。

**Comment by DuckDuckStudio** [comment]
我不太清楚macos/linux上如何配置类似windows的环境变量那样的东西。如果可以的话可以试下将对应的可执行文件添加进去
