### ISSUE TITLE
[BUG]打包版无法使用更新命令更新且检查更新时未去除-pack后缀

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Chinese_git#5]
![image](https://github.com/DuckDuckStudio/Chinese_git/assets/89643991/501d8923-f484-4555-9f09-c5226a552c1d)

**Comment by DuckDuckStudio** [comment]
![image](https://github.com/DuckDuckStudio/Chinese_git/assets/89643991/ea55c94e-8d0b-4844-bf3f-5cb2e8f23c27)

更新时未去除pack后缀

**Comment by DuckDuckStudio** [comment]
未去除`-pack`后缀的问题将在 v2.4 中修复，但由于我的某些原因，v2.4 版本的更新将无限期延后，且打包版的更新问题仍然存在...

**Comment by DuckDuckStudio** [comment]
Tag解释：
待发布部分：未去除`-pack`后缀的问题的修复
需要帮助部分：打包版无法使用命令更新

**Comment by WXZing** [comment]
已解决，已在 v2.4 中发布修正
