### ISSUE TITLE
[BUG]: Pypi上的相关问题

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Chinese_git#57]
### 在继续之前，请确认以下内容

- [X] 我已经搜索过已存在的问题，并没有存在相同的正在进行中/重复/已解决的问题
- [X] 如果该问题在预览版中被解决，我没有被告知

### 选择一个问题类别

使用问题

### 描述你遇到的问题

- https://github.com/DuckDuckStudio/Chinese_git/pull/46#issuecomment-2289395026

### 描述如何重现你遇到的问题

/

### 实际行为

/

### 预期行为

正常运行相关命令

### 版本信息

```raw
/
```

### 屏幕截图或日志 (可选)

/

**Comment by DuckDuckStudio** [comment]
如有实现方案可PR至拉取请求的分支

**Comment by nobodxbodon** [comment]
一个线索，mac下subprocess这样用就会出错：

```
>>> subprocess.run('git ' + '--version')
...
FileNotFoundError: [Errno 2] No such file or directory: 'git --version': 'git --version'
```

拆成片段就可以：
```
>>> subprocess.run(['git','--version'])
git version 2.30.1 (Apple Git-130)
```

我 [这个聚合工具](https://gitee.com/zhishi/collection-of-chinese-blogs/tree/master/%E5%8E%9F%E5%9E%8B) 正好也调用本地 git，就是先把命令 [拆成片段再run](https://gitee.com/zhishi/collection-of-chinese-blogs/blob/master/%E5%8E%9F%E5%9E%8B/git%E5%8A%9F%E7%94%A8.ul#L7)。

**Comment by DuckDuckStudio** [comment]
可是我就是用下面那样会出错才改成上面那样的...

**Comment by nobodxbodon** [comment]
问题有链接的话可以一道研究一下。
供参考：[文档里建议](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) 用序列:

>  If args is a string, the interpretation is platform-dependent and described below. See the shell and executable arguments for additional differences from the default behavior. Unless otherwise stated, **it is recommended to pass args as a sequence.**

**Comment by DuckDuckStudio** [comment]
放弃 Pipy 上的相关工作，对于参数传递问题将在下个版本中解决
